blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/Power-Components/polirium-datatable/discussions/new?category=bug
    about: Submit a bug or an issue
  - name: Ask a question
    url: https://github.com/Power-Components/polirium-datatable/discussions/new?category=q-a
    about: Ask the community for help
  - name: Request a feature
    url: https://github.com/Power-Components/polirium-datatable/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Report a security issue
    url: https://github.com/Power-Components/polirium-datatable/security/policy
    about: Learn how to notify us for sensitive bugs
